data:
  categorical_features:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - native_country
  label: salary
model_training:
  training_data_path: data/census_clean.csv
  trained_model_path: model/model.cbm
  label_encoder: model/label_encoder.pkl
  metrics_folder_path: metrics
  training_iterations: 500
  model_grid_search_hparams:
    learning_rate: 
    - 0.05
    - 0.1
    depth: 
    - 6
    - 8
    - 10
    l2_leaf_reg: 
    - 1